# **Extracción**

In [63]:
import pandas as pd 
import requests

import numpy as np

In [2]:
# URL del archivo JSON
url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'

In [3]:
# Realizar la solicitud GET al URL
response = requests.get(url)
# Verificar el código de estado de la respuesta
print(response.status_code)

200

In [4]:
# Convertir la respuesta a formato JSON
data = response.json()
# Verificar el tipo de datos obtenidos
type(data)

list

# **Transformación**

## **Conociendo el conjunto de datos**

In [5]:
# Quita estructuras anidadas presentes en el json
data = pd.json_normalize(data)

In [6]:
data.shape

(7267, 21)

In [7]:
data.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [8]:
data.tail()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [9]:
# Unifica los nombres de las columnas a todo en minúsculas y cambia '.' por '_'
data.columns = data.columns.str.lower().str.replace('.', '_')
data.head(2)

,customerid,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,...,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,account_charges_total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4

In [10]:
data.info()
# Ojo, cambiar el tipo de dato de la columna 'account_charges_total' a numérico para poder realizar análisis posteriores

<class 'pandas.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerid                 7267 non-null   str
 1   churn                      7267 non-null   str
 2   customer_gender            7267 non-null   str
 3   customer_seniorcitizen     7267 non-null   int64
 4   customer_partner           7267 non-null   str
 5   customer_dependents        7267 non-null   str
 6   customer_tenure            7267 non-null   int64
 7   phone_phoneservice         7267 non-null   str
 8   phone_multiplelines        7267 non-null   str
 9   internet_internetservice   7267 non-null   str
 10  internet_onlinesecurity    7267 non-null   str
 11  internet_onlinebackup      7267 non-null   str
 12  internet_deviceprotection  7267 non-null   str
 13  internet_techsupport       7267 non-null   str
 14  internet_streamingtv       7267 non-null   str
 15  internet_streamingmovies   7267 non-null   str
 16  account_contract           7267 non-null   str
 17  account_paperlessbilling   7267 non-null   str
 18  account_paymentmethod      7267 non-null   str
 19  account_charges_monthly    7267 non-null   float64
 20  account_charges_total      7267 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.2 MB

In [11]:
#Verificar el tipo de datos de la columna 'account_charges_total'
data['account_charges_total'].dtype

In [11]:
#Verificar los valores únicos de la columna 'account_charges_total'
data['account_charges_total'].unique()

<StringArray>
[  '593.3',   '542.4',  '280.85', '1237.85',   '267.4',  '571.45', '7904.25',
  '5377.8',  '340.35',  '5957.9',
 ...
  '3625.2',  '1517.5', '4871.45',  '6171.2',   '856.5', '4018.05',  '633.45',
   '742.9', '4627.65',  '3707.6']
Length: 6531, dtype: str

In [13]:
# Verificar los valores que esten en blanco en la columna 'account_charges_total'
(data["account_charges_total"].str.strip() == "").sum()

np.int64(11)

In [12]:
# Creación de un nuevo dataframe con los clientes que están en blanco en la columna 'account_charges_total'
df_nan_account_charges_total = data[data['account_charges_total'].str.strip() == '']
df_nan_account_charges_total.head(12)
# Ojo: Estos registros tienen en ceros la columna 'account_charges_total' pues 'customer_ternure' está en ceros también

,customerid,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,...,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,account_charges_total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [13]:
# Cambia el tipo de dato de la columna 'account_charges_total' a numérico, conviritiendo en NaN los valores en blanco
data['account_charges_total'] = pd.to_numeric(data['account_charges_total'], errors='coerce')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerid                 7267 non-null   str
 1   churn                      7267 non-null   str
 2   customer_gender            7267 non-null   str
 3   customer_seniorcitizen     7267 non-null   int64
 4   customer_partner           7267 non-null   str
 5   customer_dependents        7267 non-null   str
 6   customer_tenure            7267 non-null   int64
 7   phone_phoneservice         7267 non-null   str
 8   phone_multiplelines        7267 non-null   str
 9   internet_internetservice   7267 non-null   str
 10  internet_onlinesecurity    7267 non-null   str
 11  internet_onlinebackup      7267 non-null   str
 12  internet_deviceprotection  7267 non-null   str
 13  internet_techsupport       7267 non-null   str
 14  internet_streamingtv       7267 non-null   str
 15  internet_streamingmovies   7267 non-null   str
 16  account_contract           7267 non-null   str
 17  account_paperlessbilling   7267 non-null   str
 18  account_paymentmethod      7267 non-null   str
 19  account_charges_monthly    7267 non-null   float64
 20  account_charges_total      7256 non-null   float64
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

In [23]:
# Completa los espacios en blanco con 0
data['account_charges_total'] = data['account_charges_total'].fillna(0)
data['account_charges_total']

0        593.30
1        542.40
2        280.85
3       1237.85
4        267.40
         ...
7262     742.90
7263    1873.70
7264      92.75
7265    4627.65
7266    3707.60
Name: account_charges_total, Length: 7267, dtype: float64

In [ ]:
# Verifica que se hayan cambiado los espacios en blanco con 0
data['account_charges_total'].isna().sum()

np.int64(0)

In [29]:
#Verificar que no haya datos faltantes
data.isnull().sum()

customerid                   0
churn                        0
customer_gender              0
customer_seniorcitizen       0
customer_partner             0
customer_dependents          0
customer_tenure              0
phone_phoneservice           0
phone_multiplelines          0
internet_internetservice     0
internet_onlinesecurity      0
internet_onlinebackup        0
internet_deviceprotection    0
internet_techsupport         0
internet_streamingtv         0
internet_streamingmovies     0
account_contract             0
account_paperlessbilling     0
account_paymentmethod        0
account_charges_monthly      0
account_charges_total        0
dtype: int64

In [30]:
#Verificar que no haya datos duplicados
data.duplicated().sum()

np.int64(0)

In [31]:
#Verificar que no haya id de clientes duplicados
data[data.duplicated('customerid')]

Empty DataFrame
Columns: [customerid, churn, customer_gender, customer_seniorcitizen, customer_partner, customer_dependents, customer_tenure, phone_phoneservice, phone_multiplelines, internet_internetservice, internet_onlinesecurity, internet_onlinebackup, internet_deviceprotection, internet_techsupport, internet_streamingtv, internet_streamingmovies, account_contract, account_paperlessbilling, account_paymentmethod, account_charges_monthly, account_charges_total]
Index: []

[0 rows x 21 columns]

In [ ]:
# Verifica las entradas de 'churn'
data['churn'].unique()
# Ojo: deberían ser sólo 'Yes' o 'No'

<StringArray>
['No', 'Yes', '']
Length: 3, dtype: str

In [ ]:
# Verifica número de veces que hay de cada entrada
data['churn'].value_counts()

churn
No     5174
Yes    1869
        224
Name: count, dtype: int64

In [40]:
#Verificar el tipo de datos de la columna 'account_charges_total'
data['account_charges_monthly'].dtype

dtype('float64')

In [ ]:
# Verificar si hay valores faltantes en 'account_charges_monthly'
data['account_charges_monthly'].isna().sum()

np.int64(0)

In [ ]:
# Verificar si hay valores faltantes en 'customer_tenure'
data['customer_tenure'].isna().sum()

np.int64(0)

In [ ]:
#Verificar el tipo de datos de la columna 'account_contract'
data['account_contract'].unique()

<StringArray>
['One year', 'Month-to-month', 'Two year']
Length: 3, dtype: str

In [ ]:
# Verificar si hay valores faltantes en 'account_contract'
data['account_contract'].isna().sum()

np.int64(0)

In [50]:
# Calcular el porcentaje de clientes que han cancelado el servicio
churn_yes = data.groupby('churn').size()['Yes'] * 100 / len(data)
print(f'Porcentaje de clientes que han cancelado el servicio: {churn_yes:.2f}%')

Porcentaje de clientes que han cancelado el servicio: 25.72%

In [52]:
# Calcular el porcentaje de clientes que NO han cancelado el servicio
churn_no = data.groupby('churn').size()['No'] * 100 / len(data)
print(f'Porcentaje de clientes que NO han cancelado el servicio: {churn_no:.2f}%')

Porcentaje de clientes que NO han cancelado el servicio: 71.20%

In [58]:
# Verificar si hay valores faltantes en 'churn'
data['churn'].isna().sum()

np.int64(0)

In [64]:
# Convierte los strings vacíos en nan
data['churn'] = data['churn'].str.strip().replace("",np.nan)

In [65]:
# Verificar si se convirtieron los strings vacíos en nan
data['churn'].isna().sum()

np.int64(224)

In [70]:
data_churn_nan = data['churn'].isna().sum() * 100 / len(data)
print(f'El pocentaje de valores nan de churn es: {data_churn_nan:.2f}')
# Ojo: como son muy pocas entradas las que son nan, se eliminarán

El pocentaje de valores nan de churn es: 3.08

# **Carga y Análisis**

# **Informe Final**